name: cybernate_retail_mobile
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  json_annotation: ^4.7.0
  uuid: ^3.0.6
  sembast: ^3.3.1
  xxtea: ^2.1.0
  lottie: ^1.4.1
  shared_preferences: ^2.0.15
  mobx: ^2.0.7+5
  get_it: ^7.2.0
  mobx_codegen: ^2.0.7
  aes_crypt: ^0.1.1
  path_provider: ^2.0.11
  provider: ^6.0.4
  flutter_mobx: ^2.0.6+4
  form_builder_validators: ^8.4.0
  introduction_screen: ^3.0.2
  flutter_form_builder: ^7.7.0
  flutter_neumorphic: ^3.2.0
  rive: ^0.9.1
  font_awesome_flutter: ^10.2.1
  flutter_svg: ^1.1.6
  dotted_decoration: ^2.0.0
  chips_choice: ^3.0.0
  widget_circular_animator: ^1.0.0
  im_stepper: ^1.0.1+1
  image_picker: ^0.8.6
  intl_phone_field: ^3.1.0
  dropdown_search: ^5.0.3
  form_builder_image_picker: ^3.1.0
  rflutter_alert: ^2.0.4
  shimmer: ^2.0.0
  permission_handler: ^10.2.0
  firebase_crashlytics: ^3.0.6
  flutter_native_splash: ^2.2.15
  flutter_launcher_icons: ^0.11.0
  sentry_flutter: ^6.16.1
  google_fonts: ^3.0.1
  flutter_screenutil: ^5.6.0
  flutter_keyboard_visibility: ^5.4.0
  getwidget: ^3.0.1
  pinput: ^2.2.16
  circular_countdown_timer: ^0.2.3
  ferry: ^0.13.0
  gql_http_link: ^0.4.5
  build_runner: ^2.3.2
  hive_flutter: ^1.1.0
  ferry_hive_store: ^0.5.0
  hive: ^2.2.3
  ferry_flutter: ^0.8.0
  json_serializable: ^6.5.4
  flutter_secure_storage: ^7.0.1
  get: ^4.6.5
  toggle_switch: ^2.0.1
  google_maps_flutter: ^2.2.2
  page_transition: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ferry_generator: ^0.7.0
  
flutter:

  uses-material-design: true

  assets:
    - assets/login/
    - assets/logo/
    - assets/splash/
    - assets/icons/
    - assets/item_images/
    - assets/animations/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 700


flutter_native_splash:
  background_image: "assets/logo/logo-splash.png"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo-icon.png"