// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmzXUCzASlEpC5fjBK9_j0JymKwwCKSuE',
    appId: '1:375079949702:android:604a6b9424851769474807',
    messagingSenderId: '375079949702',
    projectId: 'cybernate-retail',
    storageBucket: 'cybernate-retail.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx6FDWQN_7zx_IaFOMtMoNqiZNNh0ZeCE',
    appId: '1:375079949702:ios:eb8f078fa57b2531474807',
    messagingSenderId: '375079949702',
    projectId: 'cybernate-retail',
    storageBucket: 'cybernate-retail.appspot.com',
    androidClientId: '375079949702-cfpn8kobi8nc18fhtkh7isf32f4dd3s8.apps.googleusercontent.com',
    iosClientId: '375079949702-54flq54n3d1hcs5d06d2j267ej5g3p73.apps.googleusercontent.com',
    iosBundleId: 'com.erstnot.cybernateRetailMobile',
  );
}
